# Generated by Django 4.2.3 on 2023-08-09 11:44

import common.custom_model_fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', common.custom_model_fields.LowercaseEmailField(db_index=True, max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=30)),
                ('last_name', models.CharField(blank=True, default='', max_length=30)),
                ('middle_name', models.CharField(blank=True, default='', max_length=30)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator('^\\+\\d{1,3}\\d{1,14}$', message='Enter valid phone number')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'female')], default='male', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('stock_balance', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In Progress'), ('canceled', 'Canceled'), ('returned', 'Returned'), ('shipped', 'Shipped'), ('shipped_back', 'Shipped Back'), ('completed', 'Completed')], default='new', max_length=30)),
                ('payment_status', models.CharField(blank=True, choices=[('not_paid', 'Not Paid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overpaid', 'Overpaid')], default='not_paid', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('place_of_delivery', models.CharField(blank=True, default='', max_length=300)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(blank=True, default=0)),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='orders.good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='orders.order')),
            ],
        ),
    ]
