# Generated by Django 4.2.3 on 2023-08-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_latest_editor_alter_order_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='vendor_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
