# Generated by Django 4.2.3 on 2023-09-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_good_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
